# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-13 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Editor',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='editors',
            new_name='editor',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, upload_to='articles/'),
        ),
    ]
